import streamlit as st
import joblib
import time
from news_api import search_news

# ---------------- PAGE CONFIG ---------------- #

st.set_page_config(
    page_title="AI News Verification System",
    page_icon="📰",
    layout="wide"
)

st.title("📰 AI News Verification System")
st.markdown(
    "Detect whether a news article is likely **Real** or **Fake** using Machine Learning "
    "and search for related online news."
)

# ---------------- LOAD MODEL ---------------- #

@st.cache_resource
def load_model():
    return joblib.load("fake_news_model.pkl")

try:
    model = load_model()
except Exception as e:
    st.error(f"Unable to load model.\n\n{e}")
    st.stop()

# ---------------- USER INPUT ---------------- #

news = st.text_area(
    "Paste News Article or Headline",
    height=220,
    placeholder="Example: ISRO successfully launched a new satellite..."
)

# ---------------- ANALYZE ---------------- #

if st.button("🔍 Analyze News", use_container_width=True):

    if not news.strip():
        st.warning("Please enter some news.")
        st.stop()

    with st.spinner("🤖 AI is analyzing the article..."):

        time.sleep(0.7)
        st.write("✔ Reading article...")

        time.sleep(0.7)
        st.write("✔ Extracting keywords...")

        time.sleep(0.7)
        st.write("✔ Comparing with trained model...")

        prediction = model.predict([news])[0]

        probabilities = model.predict_proba([news])[0]

        fake_prob = probabilities[0] * 100
        real_prob = probabilities[1] * 100

        confidence = max(fake_prob, real_prob)

        time.sleep(0.7)
        st.write("✔ Searching latest related news...")

        articles = search_news(news)

    st.divider()

    col1, col2 = st.columns([1, 2])

    # ---------------- LEFT PANEL ---------------- #

    with col1:

        st.subheader("🤖 AI Prediction")

        if prediction == 1:
            st.success("✅ REAL NEWS")
        else:
            st.error("🚨 FAKE NEWS")

        st.metric("Confidence", f"{confidence:.2f}%")

        st.progress(int(confidence))

        st.markdown("### Probability")

        st.write(f"🟢 Real : **{real_prob:.2f}%**")

        st.write(f"🔴 Fake : **{fake_prob:.2f}%**")

        st.divider()

        st.subheader("📝 Quick Summary")

        summary = ". ".join(news.split(".")[:3])

        st.info(summary)

    # ---------------- RIGHT PANEL ---------------- #

    with col2:

        st.subheader("📰 Latest Related News")

        if articles:

            for article in articles:

                with st.container():

                    st.markdown(f"### {article['title']}")

                    st.write(
                        f"**Source:** {article['source']['name']}"
                    )

                    st.write(
                        f"**Published:** {article['publishedAt']}"
                    )

                    if article["description"]:
                        st.write(article["description"])

                    st.link_button(
                        "Read Full Article",
                        article["url"]
                    )

                    st.divider()

        else:

            st.warning("No related news found.")

    # ---------------- FINAL VERDICT ---------------- #

    st.divider()

    st.subheader("📋 Final AI Verdict")

    if prediction == 1:

        st.success(
            """
### ✅ Likely Real News

The machine learning model predicts that this article is likely **REAL**.

Please compare it with the related articles shown above before sharing.
"""
        )

    else:

        st.error(
            """
### 🚨 Likely Fake News

The machine learning model predicts that this article is likely **FAKE**.

Please verify the claim using trusted news organizations before believing or sharing it.
"""
        )

    st.info(
        "⚠ This prediction is generated by an AI model and should not be treated as a final fact-check. Always verify important claims using trusted news sources."
    )